name: Build discordcf

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build discordcf
        id: build
        run: ./.github/scripts/build.sh
        shell: bash
